### ISSUE TITLE
Check every 24h?

### ISSUE THREAD

**Issue by Kraker01** [azhuge233/GOGGiveawayNotifier#1]
Hi, 

your program is running fine, but is running once and then quitting. Is it possible to add a flag or a variable in config.json to let it run endless? 

This is what i get:
C:\GOGGiveawayNotifier\GOGGiveawayNotifier\bin\Release\net5.0\win10-x64>GOGGiveawayNotifier.exe
2021-08-17 10:18:37 | INFO: - Start Job -
2021-08-17 10:18:38 | INFO: There's no giveaway currently.
2021-08-17 10:18:38 | INFO: - End Job -

**Comment by azhuge233** [comment]
I have thought about it, but I'm not planning to do this.
Under these 'console app' circumstances, I personally think it's way better to use system schedulers, adding a loop or internal scheduler will break the flexibility.
With **cron** or **Task Scheduler** you can set any running frequency.
